import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import subprocess
import os
import textwrap
from PIL import Image, ImageTk # Pillow library for image manipulation

# --- Configuration ---
# IMPORTANT: Adjust this path to your OpenSCAD executable!
# For Windows example: r"C:\Program Files\OpenSCAD\openscad.exe"
# For macOS example: "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD"
# For Linux (often in PATH): "openscad"
OPENSCAD_EXEC_PATH = r"C:\Program Files\OpenSCAD\openscad.exe" # Changed to raw string to fix escape sequence warning

# Directory to store generated SCAD files, previews, and STLs
OUTPUT_DIR = "generated_openscad_labels"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# --- OpenSCAD Template ---
# This template uses variables that will be passed via the command line (-D flag)
OPENSCAD_TEMPLATE = textwrap.dedent("""
    // OpenSCAD Generated Script for Embossed Text
    // Generated by Python GUI Script

    // External Parameters (set via -D flag from Python)
    display_text = "DEFAULT";
    font_style = "Arial"; // This will be overridden by -D
    text_size = 18;
    text_extrude_height = 2;
    plate_width = 80;
    plate_length = 30;
    plate_thickness = 5;
    emboss_type = "raised"; // "raised" or "recessed"

    // --- Modules ---
    module create_plate(width, length, thickness) {
        cube([width, length, thickness], center = true);
    }

    module create_3d_text(text_str, font_name_var, size, height) { // Renamed parameter for clarity
        linear_extrude(height = height) {
            rotate([0,0,90]) {
                text(text_str, font = font_name_var, size = size, halign = "center", valign = "center");
            }
        }
    }

    // --- Main Logic ---
    if (emboss_type == "raised") {
        union() {
            create_plate(plate_width, plate_length, plate_thickness);
            translate([0, 0, plate_thickness / 2 - (text_extrude_height / 2)]) {
                // Pass the font_style variable to the module
                create_3d_text(display_text, font_style, text_size, text_extrude_height);
            }
        }
    } else if (emboss_type == "recessed") {
        difference() {
            create_plate(plate_width, plate_length, plate_thickness);
            // Add a small epsilon (0.01) to depth to ensure clean cut
            translate([0, 0, plate_thickness / 2 - text_extrude_height + 0.01]) {
                create_3d_text(display_text, font_style, text_size, text_extrude_height + 0.1); // Extrude slightly more for a cleaner cut
            }
        }
    } else {
        echo("Error: Invalid emboss_type. Using 'raised' as default.");
        union() { // Fallback to raised if type is invalid
            create_plate(plate_width, plate_length, plate_thickness);
            translate([0, 0, plate_thickness / 2 - (text_extrude_height / 2)]) {
                create_3d_text(display_text, font_style, text_size, text_extrude_height);
            }
        }
    }
""")

class OpenSCADLabelGeneratorApp:
    FONT_MAP = {
        "Arial": {"openscad": "Arial:style=Regular", "pillow": r"C:\\Windows\\Fonts\\arial.ttf"},
        "Verdana": {"openscad": "Verdana:style=Regular", "pillow": r"C:\\Windows\\Fonts\\verdana.ttf"},
        "Times New Roman": {"openscad": "Times New Roman:style=Regular", "pillow": r"C:\\Windows\\Fonts\\times.ttf"},
        "Courier New": {"openscad": "Courier New:style=Regular", "pillow": r"C:\\Windows\\Fonts\\cour.ttf"},
        "AldotheApache": {"openscad": "Aldo the Apache", "pillow": r"C:\\Windows\\Fonts\\AldotheApache.ttf"},
    }

    def estimate_text_length_mm(self, text, font_name, font_size_pt):
        """Estimate the width of the text in mm for the given font and size using Pillow, with a larger scaling factor and padding to ensure fit."""
        try:
            from PIL import ImageFont
            pillow_font = self.FONT_MAP.get(font_name, {}).get("pillow", None)
            if pillow_font and os.path.exists(pillow_font):
                font = ImageFont.truetype(pillow_font, font_size_pt)
            else:
                if pillow_font:
                    print(f"Warning: Font file not found for {font_name}: {pillow_font}. Using default font for estimate.")
                font = ImageFont.load_default()
            bbox = font.getbbox(text)
            width_px = bbox[2] - bbox[0]
            px_to_mm = 25.4 / 96
            width_mm = width_px * px_to_mm * 4 + 25  # increased scaling and padding
            print(f"[DEBUG] Text '{text}' in font '{font_name}' width_px={width_px}, width_mm={width_mm:.2f}")
            return width_mm
        except Exception as e:
            print(f"Warning: Exception in estimate_text_length_mm: {e}. Using fallback estimate.")
            return max(20, len(text) * 10 + 30)
    def __init__(self, master):
        self.master = master
        master.title("OpenSCAD Label Generator")
        master.geometry("800x400")
        master.resizable(True, True)

        # Only one column for parameters now
        master.grid_columnconfigure(0, weight=0)
        master.grid_columnconfigure(1, weight=1)
        master.grid_rowconfigure(0, weight=1)

        self.create_widgets()
        self.load_default_preview()

    def create_widgets(self):
        # --- Parameter Frame (Left Side) ---
        self.param_frame = ttk.LabelFrame(self.master, text="Parameters", padding="10")
        self.param_frame.grid(row=0, column=0, padx=10, pady=10, sticky="nsew")
        self.param_frame.grid_columnconfigure(0, weight=1)

        # Text Input
        ttk.Label(self.param_frame, text="Label Text:").grid(row=0, column=0, sticky="w", pady=2)
        self.text_var = tk.StringVar(value="TOOLS")
        ttk.Entry(self.param_frame, textvariable=self.text_var, width=30).grid(row=1, column=0, sticky="ew", pady=2)

        # Font Selection (simple list, can be expanded)
        ttk.Label(self.param_frame, text="Font Style:").grid(row=2, column=0, sticky="w", pady=2)
        self.font_options = ["Arial", "Verdana", "Times New Roman", "Courier New", "Aldo the Apache"] # Common fonts
        self.font_var = tk.StringVar(value=self.font_options[0])
        self.font_combobox = ttk.Combobox(self.param_frame, textvariable=self.font_var, values=self.font_options, state="readonly")
        self.font_combobox.grid(row=3, column=0, sticky="ew", pady=2)
        # Allow custom font entry if not in list (optional, but useful)
        self.font_combobox.bind("<<ComboboxSelected>>", lambda event: self.font_var.set(self.font_combobox.get()))
        # You could also change state to "normal" and add validation if user types

        # Emboss Type
        ttk.Label(self.param_frame, text="Emboss Type:").grid(row=4, column=0, sticky="w", pady=2)
        self.emboss_type_var = tk.StringVar(value="raised")
        ttk.Radiobutton(self.param_frame, text="Raised", variable=self.emboss_type_var, value="raised").grid(row=5, column=0, sticky="w", padx=5)
        ttk.Radiobutton(self.param_frame, text="Recessed", variable=self.emboss_type_var, value="recessed").grid(row=6, column=0, sticky="w", padx=5)

        # --- Buttons ---
        self.button_frame = ttk.Frame(self.param_frame)
        self.button_frame.grid(row=7, column=0, columnspan=2, pady=15, sticky="ew")
        self.button_frame.grid_columnconfigure(0, weight=1)
        self.button_frame.grid_columnconfigure(1, weight=1)

        ttk.Button(self.button_frame, text="Generate Preview", command=self.generate_preview).grid(row=0, column=0, padx=5, sticky="ew")
        ttk.Button(self.button_frame, text="Export STL", command=self.export_stl).grid(row=0, column=1, padx=5, sticky="ew")

        # --- Preview Frame (Right Side) ---
        self.preview_frame = ttk.LabelFrame(self.master, text="3D Preview", padding="10")
        self.preview_frame.grid(row=0, column=1, padx=10, pady=10, sticky="nsew")
        self.preview_frame.grid_columnconfigure(0, weight=1)
        self.preview_frame.grid_rowconfigure(0, weight=1)

        self.preview_label = ttk.Label(self.preview_frame)
        self.preview_label.grid(row=0, column=0, sticky="nsew")
        self.preview_label.bind("<Configure>", self.on_preview_resize) # Bind resize event

        # Status Bar
        self.status_bar = ttk.Label(self.master, text="Ready", relief=tk.SUNKEN, anchor="w")
        self.status_bar.grid(row=1, column=0, columnspan=2, sticky="ew")

    def load_default_preview(self):
        """Loads a blank or default image when the app starts."""
        try:
            # Create a blank image
            img = Image.new('RGB', (800, 600), color = (200, 200, 200)) # Light grey background
            d = ImageDraw.Draw(img)
            d.text((img.width/2, img.height/2), "Generate a Label!", fill=(100,100,100), anchor="mm", font=ImageFont.truetype("arial.ttf", 40))
            self.tk_img = ImageTk.PhotoImage(img)
            self.preview_label.config(image=self.tk_img)
            self.status_bar.config(text="Welcome! Adjust parameters and click 'Generate Preview'.")
        except Exception as e:
            messagebox.showerror("Error", f"Could not load default preview: {e}")
            self.status_bar.config(text="Error loading default preview.")

    def on_preview_resize(self, event):
        """Callback for when the preview label is resized."""
        # This will trigger a preview regeneration to fit the new size
        # but only if a previous image exists and the size has significantly changed
        if hasattr(self, 'last_preview_size') and \
           (abs(event.width - self.last_preview_size[0]) > 10 or \
            abs(event.height - self.last_preview_size[1]) > 10):
            self.generate_preview() # Regenerate to fit new size
        self.last_preview_size = (event.width, event.height)


    def _generate_openscad_script_content(self, params):
        """Generates the OpenSCAD script content with given parameters."""
        # The template itself remains generic, parameters are passed via -D flag
        return OPENSCAD_TEMPLATE

    def _run_openscad(self, scad_filepath, output_filepath, output_format, params):
        """
        Calls the OpenSCAD executable to render the SCAD file.
        """
        command = [
            OPENSCAD_EXEC_PATH,
            scad_filepath,
            "-o", output_filepath,
            # Pass parameters using -D flag. Removed the backslash escaping for quotes
            # and rely on OpenSCAD's string concatenation to handle spaces in font names.
            f"-D display_text=\"{params['text']}\"", # Ensure text is quoted
            f"-D font_style=\"{params['font']}\"",  # Ensure font string is quoted
            f"-D text_size={params['text_size']}",
            f"-D text_extrude_height={params['text_extrude_height']}",
            f"-D plate_width={params['plate_width']}",
            f"-D plate_length={params['plate_length']}",
            f"-D plate_thickness={params['plate_thickness']}",
            f"-D emboss_type=\"{params['emboss_type']}\"", # Ensure emboss type is quoted
        ]

        if output_format == "png":
            # Get current size of the preview label for dynamic image generation
            preview_width = self.preview_label.winfo_width()
            preview_height = self.preview_label.winfo_height()
            if preview_width == 1 or preview_height == 1: # Fallback if label not yet sized
                preview_width, preview_height = 800, 600 # Fallback to a reasonable size

            command.extend(["--render", "--imgsize", f"{preview_width},{preview_height}"])
            # Add camera settings for a nice view (adjust as needed)
            command.extend(["--camera=0,0,0,60,0,45,150", "--autocenter", "--viewall"])
        elif output_format == "stl":
            command.append("--render") # Ensure full render for STL

        try:
            # Use subprocess.run for cleaner process management
            process = subprocess.run(command, capture_output=True, text=True, check=True, timeout=60) # 60 sec timeout
            if process.stderr:
                print("OpenSCAD Warnings/Errors:\n", process.stderr) # Print to console for debugging
            return True, process.stdout, process.stderr
        except FileNotFoundError:
            return False, "", f"Error: OpenSCAD executable not found at '{OPENSCAD_EXEC_PATH}'. Please configure the path."
        except subprocess.CalledProcessError as e:
            return False, e.stdout, f"OpenSCAD Error: {e.stderr}"
        except subprocess.TimeoutExpired:
            return False, "", "OpenSCAD rendering timed out."
        except Exception as e:
            return False, "", f"An unexpected error occurred: {e}"

    def get_current_parameters(self):
        """Collects all current parameter values from the GUI."""
        text = self.text_var.get()
        font = self.font_var.get()
        text_size = 18  # Fixed text size (pt)
        openscad_font = self.FONT_MAP.get(font, {}).get("openscad", font)
        plate_width = 25  # Fixed width (height of letters)
        plate_length = self.estimate_text_length_mm(text, font, text_size)
        return {
            "text": text,
            "font": openscad_font,
            "text_size": text_size,
            "text_extrude_height": 4,  # Fixed extrude height
            "plate_width": plate_width,
            "plate_length": plate_length,
            "plate_thickness": 5,  # Fixed thickness
            "emboss_type": self.emboss_type_var.get()
        }

    def generate_preview(self):
        """Generates the OpenSCAD script and renders a PNG preview."""
        params = self.get_current_parameters()
        if not params["text"].strip():
            messagebox.showwarning("Input Error", "Please enter text for the label.")
            return

        self.status_bar.config(text="Generating preview...")
        self.master.update_idletasks() # Update GUI to show status

        clean_text = params["text"].replace(" ", "_").replace("/", "_").replace("\\", "_")
        scad_filename = os.path.join(OUTPUT_DIR, f"{clean_text}_temp.scad")
        preview_filename = os.path.join(OUTPUT_DIR, f"{clean_text}_preview.png")

        # Write the SCAD script
        with open(scad_filename, "w") as f:
            f.write(self._generate_openscad_script_content(params))

        # Run OpenSCAD in a separate thread to keep GUI responsive
        import threading
        thread = threading.Thread(target=self._run_preview_thread, args=(scad_filename, preview_filename, params))
        thread.start()

    def _run_preview_thread(self, scad_filename, preview_filename, params):
        success, stdout, stderr = self._run_openscad(
            scad_filename, preview_filename, "png", params
        )

        if success:
            import time
            max_attempts = 10
            for attempt in range(max_attempts):
                try:
                    if not os.path.exists(preview_filename) or os.path.getsize(preview_filename) == 0:
                        raise IOError("File not ready")
                    img = Image.open(preview_filename)
                    img.load()  # Force actual file read
                    # Resize image to fit label while maintaining aspect ratio
                    label_width = self.preview_label.winfo_width()
                    label_height = self.preview_label.winfo_height()
                    if label_width == 1 or label_height == 1:
                        label_width, label_height = 800, 600
                    img.thumbnail((label_width, label_height), Image.Resampling.LANCZOS)
                    self.tk_img = ImageTk.PhotoImage(img)
                    self.preview_label.config(image=self.tk_img)
                    self.status_bar.config(text="Preview generated successfully.")
                    break
                except Exception as e:
                    if attempt == max_attempts - 1:
                        messagebox.showerror("Image Error", f"Could not load or display preview image: {e}")
                        self.status_bar.config(text="Error displaying preview.")
                    else:
                        time.sleep(0.15)
        else:
            messagebox.showerror("OpenSCAD Error", f"Failed to generate preview:\n{stderr}")
            self.status_bar.config(text="Preview generation failed.")
        
        # Clean up temporary SCAD file
        try:
            os.remove(scad_filename)
        except OSError as e:
            # Only warn if error is not 'file not found' (WinError 2)
            if not (hasattr(e, 'winerror') and e.winerror == 2):
                print(f"Warning: Could not remove temporary SCAD file {scad_filename}: {e}")


    def export_stl(self):
        """Generates the OpenSCAD script and exports an STL file."""
        params = self.get_current_parameters()
        if not params["text"].strip():
            messagebox.showwarning("Input Error", "Please enter text for the label.")
            return

        initial_filename = f"{params['text'].replace(' ', '_').replace('/', '_').replace('\\', '_')}_label.stl"
        stl_save_path = filedialog.asksaveasfilename(
            defaultextension=".stl",
            initialfile=initial_filename,
            initialdir=OUTPUT_DIR,
            title="Save STL File",
            filetypes=[("STL files", "*.stl"), ("All files", "*.*")]
        )

        if not stl_save_path: # User cancelled
            self.status_bar.config(text="STL export cancelled.")
            return

        self.status_bar.config(text="Exporting STL...")
        self.master.update_idletasks()

        clean_text = params["text"].replace(" ", "_").replace("/", "_").replace("\\", "_")
        scad_filename = os.path.join(OUTPUT_DIR, f"{clean_text}_temp_export.scad")

        # Write the SCAD script
        with open(scad_filename, "w") as f:
            f.write(self._generate_openscad_script_content(params))

        # Run OpenSCAD in a separate thread
        import threading
        thread = threading.Thread(target=self._run_stl_export_thread, args=(scad_filename, stl_save_path, params))
        thread.start()

    def _run_stl_export_thread(self, scad_filename, stl_save_path, params):
        success, stdout, stderr = self._run_openscad(
            scad_filename, stl_save_path, "stl", params
        )

        if success:
            messagebox.showinfo("Export Complete", f"STL file saved successfully to:\n{stl_save_path}")
            self.status_bar.config(text="STL exported successfully.")
        else:
            messagebox.showerror("OpenSCAD Error", f"Failed to export STL:\n{stderr}")
            self.status_bar.config(text="STL export failed.")

        # Clean up temporary SCAD file
        try:
            os.remove(scad_filename)
        except OSError as e:
            # Only warn if error is not 'file not found' (WinError 2)
            if not (hasattr(e, 'winerror') and e.winerror == 2):
                print(f"Warning: Could not remove temporary SCAD file {scad_filename}: {e}")


if __name__ == "__main__":
    # Add ImageDraw and ImageFont imports here, as they are part of Pillow
    # and needed for the default preview text.
    try:
        from PIL import ImageDraw, ImageFont
    except ImportError:
        messagebox.showerror("Error", "Pillow library not found. Please install it: pip install Pillow")
        exit()

    root = tk.Tk()
    app = OpenSCADLabelGeneratorApp(root)
    root.mainloop()
