import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import subprocess
import os
import textwrap
from PIL import Image, ImageTk, ImageDraw, ImageFont # Explicitly import ImageFont
import threading
import time
import re
import sys

# --- Configuration ---
# IMPORTANT: Adjust this path to your OpenSCAD executable!
# Make sure to use raw string (r"...") or double backslashes for paths
OPENSCAD_EXEC_PATH = r"C:\Program Files\OpenSCAD\openscad.exe" 

# Directory to store generated SCAD files, previews, and STLs
OUTPUT_DIR = "generated_openscad_labels"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Default padding around the text in mm
H_PADDING = 2
V_PADDING = 2

# Fixed text and plate parameters
TEXT_EXTRUDE_HEIGHT = 3
PLATE_THICKNESS = 4

# --- OpenSCAD Template for final model ---
OPENSCAD_TEMPLATE = textwrap.dedent("""
    // OpenSCAD Generated Script for Embossed Text
    // Generated by Python GUI Scripts

    // External Parameters (set via -D -D display_text=\"{params['text']}\" -D font_style=\"{params['font']}\" -D text_size={params['text_size']} ... flags from Python)
    display_text = "DEFAULT";
    font_style = "Arial";
    text_size = 18;
    text_extrude_height = 2;
    plate_width = 80;
    plate_length = 30;
    plate_thickness = 5;
    emboss_type = "raised";

    // --- Modules ---
    module create_plate(width, length, thickness) {
        cube([length, width, thickness], center = true);
    }

    module create_3d_text(text_str, font_name_var, size, height) {
        linear_extrude(height = height) {
            text(text_str, font = font_name_var, size = size, halign = "center", valign = "center");
        }
    }

    // --- Main Logic ---
    if (emboss_type == "raised") {
        union() {
            create_plate(plate_width, plate_length, plate_thickness);
            translate([0, 0, (plate_thickness / 2) + (text_extrude_height / 2)]) {
                create_3d_text(display_text, font_style, text_size, text_extrude_height);
            }
        }
    } else if (emboss_type == "recessed") {
        difference() {
            create_plate(plate_width, plate_length, plate_thickness);
            translate([0, 0, (plate_thickness / 2) - text_extrude_height + 0.01]) { // +0.01 to avoid Z-fighting
                create_3d_text(display_text, font_style, text_size, text_extrude_height + 0.1); // +0.1 to ensure full cut
            }
        }
    } else {
        echo("Error: Invalid emboss_type. Using 'raised' as default.");
        union() {
            create_plate(plate_width, plate_length, plate_thickness);
            translate([0, 0, (plate_thickness / 2) + (text_extrude_height / 2)]) {
                create_3d_text(display_text, font_style, text_size, text_extrude_height);
            }
        }
    }
""")

# OpenSCAD template for measuring text - using textmetrics and specific echo format
MEASURE_TEXT_SCAD_TEMPLATE = textwrap.dedent("""
    $fn = 100;
    $experimental = 1; // Required for textmetrics

    // Define variables using parameters passed from Python
    text_val = "{text_val}";
    size_val = {size_val};
    font_val = "{font_val}";

    // Measure the text
    measurement = textmetrics(text=text_val, size=size_val, font=font_val);
    
    // Output the measurements
    // Access the 'size' property which is an [x,y] array
    echo("PYTHON_BBOX_START");
    echo(str("X:", measurement.size.x));  // This will output ECHO: "X:VALUE"
    echo(str("Y:", measurement.size.y));  // This will output ECHO: "Y:VALUE"
    echo(str("Z:", 0));                   // This will output ECHO: "Z:0"
    echo("PYTHON_BBOX_END");

    // Render a minimal object to ensure OpenSCAD evaluates the script and outputs echoes
    cube(0.01); 
""")


class OpenSCADLabelGeneratorApp:
    # A mapping from display names to OpenSCAD font names and their approximate
    # .ttf paths for Pillow preview. User might need to adjust .ttf paths.
    FONT_MAP = {
        "Arial": {"openscad": "Arial", "pillow": r"C:\Windows\Fonts\arial.ttf"},
        "Verdana": {"openscad": "Verdana", "pillow": r"C:\Windows\Fonts\verdana.ttf"},
        "Times New Roman": {"openscad": "Times New Roman", "pillow": r"C:\Windows\Fonts\times.ttf"},
        "Courier New": {"openscad": "Courier New", "pillow": r"C:\Windows\Fonts\cour.ttf"},
        # IMPORTANT: Updated Aldo the Apache path based on common Windows font installation
        # If this font is system-wide, it's usually in C:\Windows\Fonts
        # If it's a user-installed font, it might be in AppData, but C:\Windows\Fonts is more common
        "Aldo the Apache": {"openscad": "Aldo the Apache", "pillow": r"C:\Windows\Fonts\AldotheApache.ttf"},
    }

    # This size seems to work well for OpenSCAD textmetrics and is a good base.
    # OpenSCAD text size is roughly equivalent to font size in millimeters.
    TEXT_SIZE_MM = 18 

    def __init__(self, master):
        self.master = master
        master.title("OpenSCAD Label Generator")
        master.geometry("800x450")
        master.resizable(True, True)

        master.grid_columnconfigure(0, weight=0)
        master.grid_columnconfigure(1, weight=1)
        master.grid_rowconfigure(0, weight=1)

        self.create_widgets()
        self.load_default_preview()

    def create_widgets(self):
        self.param_frame = ttk.LabelFrame(self.master, text="Parameters", padding="10")
        self.param_frame.grid(row=0, column=0, padx=10, pady=10, sticky="nsew")
        self.param_frame.grid_columnconfigure(0, weight=1)

        ttk.Label(self.param_frame, text="Label Text:").grid(row=0, column=0, sticky="w", pady=2)
        self.text_var = tk.StringVar(value="TOOLS")
        ttk.Entry(self.param_frame, textvariable=self.text_var, width=30).grid(row=1, column=0, sticky="ew", pady=2)

        ttk.Label(self.param_frame, text="Font Style:").grid(row=2, column=0, sticky="w", pady=2)
        self.font_options = list(self.FONT_MAP.keys())
        self.font_var = tk.StringVar(value=self.font_options[0])
        self.font_combobox = ttk.Combobox(self.param_frame, textvariable=self.font_var, values=self.font_options, state="readonly")
        self.font_combobox.grid(row=3, column=0, sticky="ew", pady=2)
        self.font_combobox.bind("<<ComboboxSelected>>", lambda event: self.font_var.set(self.font_combobox.get()))

        ttk.Label(self.param_frame, text="Emboss Type:").grid(row=4, column=0, sticky="w", pady=2)
        self.emboss_type_var = tk.StringVar(value="raised")
        ttk.Radiobutton(self.param_frame, text="Raised", variable=self.emboss_type_var, value="raised").grid(row=5, column=0, sticky="w", padx=5)
        ttk.Radiobutton(self.param_frame, text="Recessed", variable=self.emboss_type_var, value="recessed").grid(row=6, column=0, sticky="w", padx=5)

        ttk.Label(self.param_frame, text="Horizontal Padding (mm):").grid(row=7, column=0, sticky="w", pady=2)
        self.h_padding_var = tk.DoubleVar(value=H_PADDING)
        ttk.Spinbox(self.param_frame, from_=0.0, to_=20.0, increment=0.5, textvariable=self.h_padding_var, width=10).grid(row=8, column=0, sticky="ew", pady=2)

        ttk.Label(self.param_frame, text="Vertical Padding (mm):").grid(row=9, column=0, sticky="w", pady=2)
        self.v_padding_var = tk.DoubleVar(value=V_PADDING)
        ttk.Spinbox(self.param_frame, from_=0.0, to_=20.0, increment=0.5, textvariable=self.v_padding_var, width=10).grid(row=10, column=0, sticky="ew", pady=2)

        self.button_frame = ttk.Frame(self.param_frame)
        self.button_frame.grid(row=11, column=0, columnspan=2, pady=15, sticky="ew")
        self.button_frame.grid_columnconfigure(0, weight=1)
        self.button_frame.grid_columnconfigure(1, weight=1)

        ttk.Button(self.button_frame, text="Generate Preview", command=self.generate_preview).grid(row=0, column=0, padx=5, sticky="ew")
        ttk.Button(self.button_frame, text="Export STL", command=self.export_stl).grid(row=0, column=1, padx=5, sticky="ew")

        self.preview_frame = ttk.LabelFrame(self.master, text="3D Preview", padding="10")
        self.preview_frame.grid(row=0, column=1, padx=10, pady=10, sticky="nsew")
        self.preview_frame.grid_columnconfigure(0, weight=1)
        self.preview_frame.grid_rowconfigure(0, weight=1)

        self.preview_label = ttk.Label(self.preview_frame)
        self.preview_label.grid(row=0, column=0, sticky="nsew")
        self.preview_label.bind("<Configure>", self.on_preview_resize)

        self.status_bar = ttk.Label(self.master, text="Ready", relief=tk.SUNKEN, anchor="w")
        self.status_bar.grid(row=1, column=0, columnspan=2, sticky="ew")

    def load_default_preview(self):
        """Loads a default image into the preview label."""
        try:
            img = Image.new('RGB', (800, 600), color=(200, 200, 200))
            d = ImageDraw.Draw(img)
            try:
                # Use a Pillow-compatible font path from FONT_MAP
                font_path = self.FONT_MAP.get("Arial", {}).get("pillow")
                font = ImageFont.truetype(font_path, 40) if font_path else ImageFont.load_default()
            except IOError:
                font = ImageFont.load_default()
            d.text((img.width / 2, img.height / 2), "Generate a Label!", fill=(100, 100, 100), anchor="mm", font=font)
            self.tk_img = ImageTk.PhotoImage(img)
            self.preview_label.config(image=self.tk_img)
            self.status_bar.config(text="Welcome! Adjust parameters and click 'Generate Preview'.")
        except Exception as e:
            print(f"Error loading default preview: {e}", file=sys.stderr)
            self.status_bar.config(text="Error loading default preview. Check terminal.")

    def on_preview_resize(self, event):
        """Regenerates the preview if the preview window is resized significantly."""
        if hasattr(self, 'last_preview_size') and \
           (abs(event.width - self.last_preview_size[0]) > 10 or \
            abs(event.height - self.last_preview_size[1]) > 10):
            if event.width > 10 and event.height > 10: # Ensure valid dimensions
                self.generate_preview()
        self.last_preview_size = (event.width, event.height)

    def _measure_text_in_openscad(self, text, font_style, text_size):
        """
        Measures the bounding box of text using OpenSCAD's textmetrics function.
        Returns (width, height, depth) or (None, None, None) on failure.
        """
        temp_scad_content = MEASURE_TEXT_SCAD_TEMPLATE.format(
            text_val=text.replace('"', '\\"'), # Escape quotes for SCAD string
            font_val=font_style.replace('"', '\\"'), # Escape quotes
            size_val=text_size
        )
        temp_scad_filename = os.path.join(OUTPUT_DIR, "temp_measure_text.scad")
        try:
            with open(temp_scad_filename, "w") as f:
                f.write(temp_scad_content)
            print(f"[DEBUG] Generated temp SCAD for measurement: {temp_scad_filename}")

            # Prepare environment variables for OpenSCAD font paths
            env_vars = os.environ.copy()
            
            # OpenSCAD's internal font directory
            openscad_install_dir = os.path.dirname(OPENSCAD_EXEC_PATH)
            openscad_fontconfig_dir = os.path.join(openscad_install_dir, "fonts") 
            
            # Ensure FONTCONFIG_PATH includes OpenSCAD's font directory
            current_fontconfig_path = env_vars.get('FONTCONFIG_PATH', '')
            if openscad_fontconfig_dir not in current_fontconfig_path.split(os.pathsep):
                env_vars['FONTCONFIG_PATH'] = openscad_fontconfig_dir + os.pathsep + current_fontconfig_path
            
            # Try to find and set the main fontconfig configuration file if not already set
            if 'FONTCONFIG_FILE' not in env_vars:
                try:
                    conf_files = [f for f in os.listdir(openscad_fontconfig_dir) if f.endswith('.conf')]
                    if conf_files:
                        main_conf = next((f for f in conf_files if 'local.conf' in f or 'fonts.conf' in f), conf_files[0])
                        env_vars['FONTCONFIG_FILE'] = os.path.join(openscad_fontconfig_dir, main_conf)
                except Exception as e:
                    print(f"Warning: Could not set FONTCONFIG_FILE: {e}", file=sys.stderr)
            
            # Add common Windows font paths to OPENSCAD_FONT_PATH
            paths_to_add_to_openscad_font_path = [
                r"C:\WINDOWS\fonts",
                os.path.join(os.path.expanduser("~"), r"AppData\Local\Microsoft\Windows\Fonts"),
                os.path.join(os.path.expanduser("~"), r"AppData\Roaming\SPB_Data\.local\share\fonts"), # Example user font path
            ]
            
            current_openscad_font_path = env_vars.get('OPENSCAD_FONT_PATH', '').split(os.pathsep)
            for p in paths_to_add_to_openscad_font_path:
                if p not in current_openscad_font_path and os.path.exists(p):
                    current_openscad_font_path.append(p)
            # Add OpenSCAD's own font dir if it's not already there
            if openscad_fontconfig_dir not in current_openscad_font_path and os.path.exists(openscad_fontconfig_dir):
                current_openscad_font_path.append(openscad_fontconfig_dir)

            env_vars['OPENSCAD_FONT_PATH'] = os.pathsep.join(filter(None, current_openscad_font_path))

            print(f"[DEBUG] FONTCONFIG_PATH: {env_vars.get('FONTCONFIG_PATH')}")
            print(f"[DEBUG] FONTCONFIG_FILE: {env_vars.get('FONTCONFIG_FILE')}")
            print(f"[DEBUG] OPENSCAD_FONT_PATH: {env_vars.get('OPENSCAD_FONT_PATH')}")


            # Command to run OpenSCAD to force evaluation and capture output
            # We use --render and output to a dummy PNG to ensure full evaluation of `echo` statements
            command = [
                OPENSCAD_EXEC_PATH,
                temp_scad_filename,
                "-o", os.path.join(OUTPUT_DIR, "dummy_measurement.png"),
                "--render",
                # For debugging, remove --quiet if you need to see all OpenSCAD's internal messages
                # "--quiet", 
                "--enable=textmetrics"
            ]
            
            print(f"[DEBUG] Running OpenSCAD measurement command: {' '.join(command)}")
            process = subprocess.run(command, capture_output=True, text=True, check=False, timeout=30, env=env_vars)

            # Clean up the dummy output file immediately
            dummy_file = os.path.join(OUTPUT_DIR, "dummy_measurement.png")
            if os.path.exists(dummy_file):
                os.remove(dummy_file)

            # Print detailed debug info, even if there are errors, to help diagnose
            print("\nOpenSCAD Measurement Process Output:")
            print("STDOUT:", process.stdout)
            print("STDERR:", process.stderr)

            if process.returncode != 0:
                print(f"ERROR: OpenSCAD exited with code {process.returncode} during text measurement.", file=sys.stderr)
                print(f"Check the OpenSCAD output above for details. Font issues are common.", file=sys.stderr)
                # Display messagebox only from the main thread
                self.master.after(0, lambda: messagebox.showerror("OpenSCAD Error", "OpenSCAD failed to measure text. Check console for details. (Font issues common)"))
                return None, None, None

            # --- CRITICAL PARSING FIX: Updated Regex and ensured stderr is processed ---
            bbox = {}
            capture_mode = False
            
            # OpenSCAD frequently sends ECHO and other messages to stderr when run via CLI.
            # We must process stderr to capture the echoed bounding box values.
            # Process STDERR lines
            for line in process.stderr.splitlines():
                if "PYTHON_BBOX_START" in line:
                    capture_mode = True
                    continue
                if "PYTHON_BBOX_END" in line:
                    capture_mode = False
                    break # Stop capturing after END marker
                if capture_mode:
                    # UPDATED REGEX to account for quotes: ECHO: "X:VALUE"
                    match_x = re.match(r'ECHO: "X:(-?\d+\.?\d*)"', line)
                    match_y = re.match(r'ECHO: "Y:(-?\d+\.?\d*)"', line)
                    match_z = re.match(r'ECHO: "Z:(-?\d+\.?\d*)"', line)

                    if match_x:
                        try: bbox['x'] = float(match_x.group(1))
                        except ValueError: print(f"Warning: Could not convert bbox_x to float: {line}", file=sys.stderr)
                    elif match_y:
                        try: bbox['y'] = float(match_y.group(1))
                        except ValueError: print(f"Warning: Could not convert bbox_y to float: {line}", file=sys.stderr)
                    elif match_z:
                        try: bbox['z'] = float(match_z.group(1))
                        except ValueError: print(f"Warning: Could not convert bbox_z to float: {line}", file=sys.stderr)
            
            # --- END CRITICAL PARSING FIX ---

            # Verify if all dimensions were captured
            if all(k in bbox for k in ['x', 'y', 'z']):
                # textmetrics for 2D text will often report Z as 0.
                # We need a non-zero height for the 3D text.
                actual_z = TEXT_EXTRUDE_HEIGHT 
                print(f"[DEBUG] OpenSCAD measured text bbox: X={bbox['x']:.2f}, Y={bbox['y']:.2f}, Z={actual_z:.2f}")
                return bbox['x'], bbox['y'], actual_z
            else:
                print(f"ERROR: Failed to parse complete text dimensions from OpenSCAD output. Captured: {bbox}", file=sys.stderr)
                print("This might be due to a font not found or an issue with textmetrics in OpenSCAD.", file=sys.stderr)
                self.master.after(0, lambda: messagebox.showerror("Measurement Error", "Failed to measure text dimensions. Ensure the selected font is installed and OpenSCAD works correctly with it."))
                return None, None, None
        except FileNotFoundError:
            self.master.after(0, lambda: messagebox.showerror("Error", f"OpenSCAD executable not found at '{OPENSCAD_EXEC_PATH}'. Please check the path in the script."))
            return None, None, None
        except subprocess.TimeoutExpired:
            self.master.after(0, lambda: messagebox.showerror("Error", "OpenSCAD text measurement timed out."))
            return None, None, None
        except Exception as e:
            self.master.after(0, lambda: messagebox.showerror("Error", f"An unexpected error occurred during text measurement: {e}"))
            print(f"ERROR: An unexpected error occurred during text measurement: {e}", file=sys.stderr)
            return None, None, None
        finally:
            # Clean up the temporary SCAD file
            try:
                if os.path.exists(temp_scad_filename):
                    os.remove(temp_scad_filename)
            except OSError as e:
                print(f"Warning: Could not remove temporary SCAD file {temp_scad_filename}: {e}", file=sys.stderr)

    def _generate_openscad_script_content(self):
        """Returns the main OpenSCAD template content."""
        return OPENSCAD_TEMPLATE

    def _run_openscad(self, scad_filepath, output_filepath, output_format, params):
        """
        Runs OpenSCAD to generate the model or preview.
        Returns (success: bool, stdout: str, stderr: str).
        """
        env_vars = os.environ.copy()
        
        # Ensure FONTCONFIG_PATH includes OpenSCAD's font directory
        openscad_install_dir = os.path.dirname(OPENSCAD_EXEC_PATH)
        openscad_fontconfig_dir = os.path.join(openscad_install_dir, "fonts") 
        current_fontconfig_path = env_vars.get('FONTCONFIG_PATH', '')
        if openscad_fontconfig_dir not in current_fontconfig_path.split(os.pathsep):
            env_vars['FONTCONFIG_PATH'] = openscad_fontconfig_dir + os.pathsep + current_fontconfig_path
        
        # Try to find and set the main fontconfig configuration file if not already set
        if 'FONTCONFIG_FILE' not in env_vars:
            try:
                conf_files = [f for f in os.listdir(openscad_fontconfig_dir) if f.endswith('.conf')]
                if conf_files:
                    main_conf_file = next((f for f in conf_files if 'local.conf' in f or 'fonts.conf' in f), conf_files[0])
                    env_vars['FONTCONFIG_FILE'] = os.path.join(openscad_fontconfig_dir, main_conf_file)
            except Exception as e:
                print(f"Warning: Could not set FONTCONFIG_FILE for main render: {e}", file=sys.stderr)

        # Add common Windows font paths to OPENSCAD_FONT_PATH
        paths_to_add_to_openscad_font_path = [
            r"C:\WINDOWS\fonts",
            os.path.join(os.path.expanduser("~"), r"AppData\Local\Microsoft\Windows\Fonts"),
            os.path.join(os.path.expanduser("~"), r"AppData\Roaming\SPB_Data\.local\share\fonts"),
        ]
        current_openscad_font_path = env_vars.get('OPENSCAD_FONT_PATH', '').split(os.pathsep)
        for p in paths_to_add_to_openscad_font_path:
            if p not in current_openscad_font_path and os.path.exists(p):
                current_openscad_font_path.append(p)
        # Add OpenSCAD's own font dir if it's not already there
        if openscad_fontconfig_dir not in current_openscad_font_path and os.path.exists(openscad_fontconfig_dir):
            current_openscad_font_path.append(openscad_fontconfig_dir)

        env_vars['OPENSCAD_FONT_PATH'] = os.pathsep.join(filter(None, current_openscad_font_path))

        command = [
            OPENSCAD_EXEC_PATH,
            scad_filepath,
            "-o", output_filepath,
            f"-D display_text=\"{params['text']}\"",
            f"-D font_style=\"{params['font']}\"",
            f"-D text_size={params['text_size']}",
            f"-D text_extrude_height={params['text_extrude_height']}",
            f"-D plate_width={params['plate_width']}",
            f"-D plate_length={params['plate_length']}",
            f"-D plate_thickness={params['plate_thickness']}",
            f"-D emboss_type=\"{params['emboss_type']}\"",
            "--enable=textmetrics" # Pass this for consistency, though textmetrics isn't used in main template
        ]

        if output_format == "png":
            # Get current size of preview_label, or use defaults
            preview_width = self.preview_label.winfo_width()
            preview_height = self.preview_label.winfo_height()
            if preview_width < 100 or preview_height < 100: # Fallback for initial state or very small window
                preview_width, preview_height = 800, 600

            # REMOVED `--colorscheme=StlColors` here as it was causing OpenSCAD errors
            command.extend([
                "--render",
                "--imgsize", f"{preview_width},{preview_height}",
                "--camera=0,0,0,60,0,45,150", # Standard camera settings
                "--autocenter",
                "--viewall" 
            ])
        elif output_format == "stl":
            command.append("--render") # --render is crucial for STL export

        try:
            print(f"[DEBUG] Running OpenSCAD render command: {' '.join(command)}")
            # Use check=False to capture stderr even if OpenSCAD returns a non-zero code,
            # as it might include warnings that aren't fatal.
            process = subprocess.run(command, capture_output=True, text=True, check=False, timeout=60, env=env_vars)
            
            if process.returncode != 0:
                print(f"OpenSCAD Render Error (return code {process.returncode}):", file=sys.stderr)
                print("STDOUT:", process.stdout, file=sys.stderr)
                print("STDERR:", process.stderr, file=sys.stderr)
                return False, process.stdout, process.stderr
            else:
                if process.stderr:
                    print("OpenSCAD Warnings/Messages during render:\n", process.stderr, file=sys.stderr)
                return True, process.stdout, process.stderr
        except FileNotFoundError:
            return False, "", f"Error: OpenSCAD executable not found at '{OPENSCAD_EXEC_PATH}'. Please configure the path."
        except subprocess.TimeoutExpired:
            return False, "", "OpenSCAD rendering timed out."
        except Exception as e:
            return False, "", f"An unexpected error occurred during render: {e}"

    def get_current_parameters(self):
        """
        Gathers current GUI parameters and calculates plate dimensions based on text measurement.
        Returns (dict of parameters, error_message: str or None).
        """
        text = self.text_var.get().strip()
        font_name_key = self.font_var.get()
        openscad_font = self.FONT_MAP.get(font_name_key, {}).get("openscad", font_name_key)

        if not text:
            return None, "Please enter text for the label."

        # Measure text using OpenSCAD
        bbox_x, bbox_y, bbox_z = self._measure_text_in_openscad(text, openscad_font, self.TEXT_SIZE_MM)

        if bbox_x is None: # Measurement failed
            return None, "Failed to measure text dimensions with OpenSCAD. Check console for details."

        # Calculate plate dimensions with padding
        plate_length = bbox_x + (self.h_padding_var.get() * 2)
        plate_width = bbox_y + (self.v_padding_var.get() * 2)

        # Ensure minimum plate size to avoid issues with very small text or zero padding
        plate_length = max(plate_length, 10) 
        plate_width = max(plate_width, 10)

        print(f"[DEBUG] Calculated plate dimensions: Length={plate_length:.2f}, Width={plate_width:.2f}")

        return {
            "text": text,
            "font": openscad_font,
            "text_size": self.TEXT_SIZE_MM, # Use the consistent TEXT_SIZE_MM
            "text_extrude_height": TEXT_EXTRUDE_HEIGHT,
            "plate_width": plate_width,
            "plate_length": plate_length,
            "plate_thickness": PLATE_THICKNESS,
            "emboss_type": self.emboss_type_var.get()
        }, None

    def generate_preview(self):
        """Initiates the generation of the 3D model preview."""
        params, error_msg = self.get_current_parameters()
        if error_msg:
            messagebox.showwarning("Input Error", error_msg)
            self.status_bar.config(text=f"Input Error: {error_msg}")
            return

        self.status_bar.config(text="Generating preview...")
        self.master.update_idletasks() # Update GUI to show status immediately

        # Create unique filenames for SCAD and PNG
        clean_text = re.sub(r'[^\w\-_\.]', '', params["text"].replace(" ", "_"))[:50] # Sanitize filename
        timestamp = int(time.time())
        scad_filename = os.path.join(OUTPUT_DIR, f"{clean_text}_{timestamp}_preview.scad")
        preview_filename = os.path.join(OUTPUT_DIR, f"{clean_text}_{timestamp}_preview.png")

        # Write the main SCAD content to a file
        with open(scad_filename, "w") as f:
            f.write(self._generate_openscad_script_content())

        # Run OpenSCAD in a separate thread to prevent GUI freeze
        thread = threading.Thread(target=self._run_preview_thread, args=(scad_filename, preview_filename, params))
        thread.start()

    def _run_preview_thread(self, scad_filename, preview_filename, params):
        """Thread target for running OpenSCAD to generate a preview image."""
        success, stdout, stderr = self._run_openscad(
            scad_filename, preview_filename, "png", params
        )

        if success:
            max_attempts = 10
            for attempt in range(max_attempts):
                try:
                    if not os.path.exists(preview_filename) or os.path.getsize(preview_filename) == 0:
                        raise IOError("File not ready or empty")

                    img = Image.open(preview_filename)
                    img.load() # Ensure image data is loaded
                    
                    # Get actual label dimensions to resize preview accurately
                    label_width = self.preview_label.winfo_width()
                    label_height = self.preview_label.winfo_height()
                    if label_width < 100 or label_height < 100: # Fallback
                        label_width, label_height = 800, 600

                    img.thumbnail((label_width, label_height), Image.Resampling.LANCZOS)
                    self.tk_img = ImageTk.PhotoImage(img)
                    self.master.after(0, lambda: self.preview_label.config(image=self.tk_img)) # Corrected
                    self.master.after(0, lambda: self.status_bar.config(text="Preview generated successfully.")) 
                    break # Exit loop on success
                except Exception as e:
                    if attempt == max_attempts - 1:
                        print(f"ERROR: Could not load or display preview image after multiple attempts: {e}", file=sys.stderr)
                        self.master.after(0, lambda: self.status_bar.config(text="Error displaying preview. Check terminal.")) 
                    else:
                        time.sleep(0.2) # Wait a bit before retrying
        else:
            print(f"ERROR: Failed to generate preview: {stderr}", file=sys.stderr)
            self.master.after(0, lambda: self.status_bar.config(text="Preview generation failed. Check terminal."))

        # Clean up the temporary SCAD file
        try:
            if os.path.exists(scad_filename):
                os.remove(scad_filename)
        except OSError as e:
            print(f"Warning: Could not remove temporary SCAD file {scad_filename}: {e}", file=sys.stderr)

    def export_stl(self):
        """Initiates the export of the 3D model to an STL file."""
        params, error_msg = self.get_current_parameters()
        if error_msg:
            messagebox.showwarning("Input Error", error_msg)
            self.status_bar.config(text=f"Input Error: {error_msg}")
            return

        initial_filename = f"{re.sub(r'[^\w\-_\.]', '', params['text'].replace(' ', '_'))[:50]}_label.stl"
        stl_save_path = filedialog.asksaveasfilename(
            defaultextension=".stl",
            initialfile=initial_filename,
            initialdir=OUTPUT_DIR,
            title="Save STL File",
            filetypes=[("STL files", "*.stl"), ("All files", "*.*")]
        )

        if not stl_save_path:
            self.status_bar.config(text="STL export cancelled.")
            return

        self.status_bar.config(text="Exporting STL...")
        self.master.update_idletasks()

        clean_text = re.sub(r'[^\w\-_\.]', '', params["text"].replace(" ", "_"))[:50]
        timestamp = int(time.time())
        scad_filename = os.path.join(OUTPUT_DIR, f"{clean_text}_{timestamp}_export.scad")

        with open(scad_filename, "w") as f:
            f.write(self._generate_openscad_script_content())

        thread = threading.Thread(target=self._run_stl_export_thread, args=(scad_filename, stl_save_path, params))
        thread.start()

    def _run_stl_export_thread(self, scad_filename, stl_save_path, params):
        """Thread target for running OpenSCAD to export an STL file."""
        success, stdout, stderr = self._run_openscad(
            scad_filename, stl_save_path, "stl", params
        )

        if success:
            self.master.after(0, lambda: self.status_bar.config(text=f"STL file saved successfully to: {stl_save_path}"))
            self.master.after(0, lambda: messagebox.showinfo("Export Success", f"STL file saved successfully to:\n{stl_save_path}"))
        else:
            print(f"ERROR: Failed to export STL: {stderr}", file=sys.stderr)
            self.master.after(0, lambda: self.status_bar.config(text="STL export failed. Check terminal."))
            self.master.after(0, lambda: messagebox.showerror("Export Failed", "Failed to export STL. Check terminal for details."))

        try:
            os.remove(scad_filename)
        except OSError as e:
            print(f"Warning: Could not remove temporary SCAD file {scad_filename}: {e}", file=sys.stderr)


if __name__ == "__main__":
    root = tk.Tk()
    app = OpenSCADLabelGeneratorApp(root)
    root.mainloop()